name: branchtag

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v*'

  
jobs:
  branchtag:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
