name: build_and_test

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    test:
        runs-on: [ubuntu-latest]
        steps:
            - name: test
              run: |
                  echo test
