name: build_and_test

on:
    push:
        tags: 
            - v1.*

jobs:
    test:
        runs-on: [ubuntu-latest]
        steps:
            - name: test
              run: |
                  echo test
