name: commentcheck
on:
  issue_comment:
    types: [created, edited, deleted]
    
jobs:
 job01:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'commenttest')
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: get pullrequest url
        run: |
          echo ${{ github.event.issue.pull_request.url }}
      - name: get upstream repo
        id: upstreamrepo
        run: |
          echo "::set-output name=reponame::$(curl -v -H "Accept: application/vnd.github.sailor-v-preview+json" -u ${{ secrets.PAT }} ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"
      - name: echo upstream repo
        run: |
          echo ${{ steps.upstreamrepo.outputs.reponame }}
      - name: Checkout upstream repo
        uses: actions/checkout@v2
        with:
           ref: ${{ steps.upstreamrepo.outputs.reponame }}
