name: commentcheck
on:
  push:
  issue_comment:
    types: [created, edited, deleted]
    
jobs:
 job01:
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
