name: pushevent
on: 
  push:
    branches: 
      - master
jobs:
  pushevent:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: create release
        run: |
          curl -v -X POST -u ${{ secrets.PAT }} -H "Accept: application/vnd.github.antiope-preview+json" --data '{"tag_name": "v2.4", "target_commitish": "master", "name": "v2.4"}' https://api.github.com/repos/weide-zhou/ticket17/releases
