name: schedule3
on:
  schedule:
    - cron: '*/6 * * * *'    
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: test1
      - name: test1
        run: echo test1
   
